### ISSUE TITLE
Ejercicio 1 H

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5#10]
# Ejercicio 1 H

### Como se interpreta una curva dead band?

**Comment by recursosssbb** [comment]
Ejercicio 1 H
Como se interpreta una curva dead band?

Términos Relacionados con la Exactitud (Calidad de la Medición)=BANDA MUERTA (DEAD BAND)

Es el rango en el que : La entrada varía sin que se inicie una respuesta observable. Se expresa como un porcentaje del Span. Está relacionada con la sensibilidad



![Image](https://user-images.githubusercontent.com/77708311/191295542-2adad4c5-afb9-49fe-b016-34b1ba1521f1.png)
