### ISSUE TITLE
Ejercicio 1 K

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5#13]
# Ejercicio 1 K

### Porque es conviene que un sensor tenga una respuesta lineal

**Comment by ernesto0369** [comment]
[Practica 2da semana Ejercicio 1 K - Ernesto Canio.pdf](https://github.com/ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5/files/9630375/Practica.2da.semana.Ejercicio.1.K.-.Ernesto.Canio.pdf)
