### ISSUE TITLE
Ejercicio 2

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5#14]
# Ejercicio 2

**Comment by ernesto0369** [comment]
[Practica 2da semana Ejercicio 2 -  Ernesto Canio.pdf](https://github.com/ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5/files/9630376/Practica.2da.semana.Ejercicio.2.-.Ernesto.Canio.pdf)
