### ISSUE TITLE
Ejercicio 4

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5#16]
# Ejercicio 4

### ¿Cual sensor ofrece la mayor exactitud y cual ofrece la mayor precision?

![imagen](https://user-images.githubusercontent.com/105946879/190526708-81e67b9d-03b3-4946-9ea5-02b7bb812d02.png)

**Comment by ernesto0369** [comment]
[Practica 2da semana Ejercicio 4 -  Ernesto Canio.pdf](https://github.com/ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5/files/9630377/Practica.2da.semana.Ejercicio.4.-.Ernesto.Canio.pdf)
