### ISSUE TITLE
Ejercicio 1 B

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5#4]
# Ejercicio 1 B

### Enumere las características estáticas de un sensor.

**Comment by recursosssbb** [comment]
**Características estáticas de sensores.**

**Las principales características que especifican los sensores son:**

      **Exactitud - Fidelidad - Sensibilidad**
 
**Exactitud (accuracy).**

Cualidad que caracteriza la capacidad de un instrumento de medida de dar indicaciones que se aproximen al verdadero valor de la magnitud medida. La exactitud de un sensor se determina mediante la denominada calibración estática.

Por ejemplo, dado un sistema de medición de temperatura, de precisión 0,05 ºC, cuando su lectura fuese de 37,2ºC significa que la temperatura del ambiente medido está entre 37,15 y 37,25 ºC.

 
**Fidelidad (precisión).**

Es la cualidad que caracteriza la capacidad de un instrumento de medida de dar el mismo valor de la magnitud medida, al medir varias veces en unas condiciones determinadas.

 

Habitualmente, la precisión se expresa como porcentaje de la escala completa. Por ejemplo, un termómetro cuyo tope de escala fuese 100ºC y de precisión 0,5% significa que toda lectura de T ºC estará sujeta a una imprecisión de 0,5ºC (si se mide 37,2ºC, la temperatura estará entre 36,7 y 37,7 ºC).

 

La precisión está asociada al cálculo de la desviación estándar del instrumento o de un procedimiento analítico.
Sensibilidad (sensivility).

Cualidad que caracteriza la capacidad de un instrumento de medida para detectar la mínima sensación que le hace provocar una variación.

**La sensibilidad** se expresa cuantitativamente mediante la tasa de cambio de la medición respecto del cambio en la especie medida.

Es común (pero erróneo) asociar la sensibilidad a la escala de lectura; p.e. si una escala de temperatura tiene divisiones cada un grado centígrado, se podría pensar que la sensibilidad fuese de ½ grado porque no sería posible "estimar" valores como ¼ de grado. En realidad, es posible que el sistema  necesite un cambió de uno antes de modificar su aguja indicadora.

 Otras caracerísticas también empleadas son:
ERROR ABSOLUTO - ERROR DE NO LINEALIDAD - REPETIBILIDAD - REPRODUCIBILIDAD - RESOLUCIÓN - RANGO DE MEDIDA - RANGO DE TRABAJO O DE OPERACIÓN - BANDA MUERTA - OFFSET O DESPLAZAMIENTO DEL CERO - TIEMPO DE RESPUESTA - HISTÉRESIS - .FUNCIÓN DE TRANSFERENCIA

**ERROR ABSOLUTO.**

Expresa la diferencia entre la magnitud medida y la lectura instrumental. En toda aplicación se desearía que el error fuese 0; sin embargo, todo los instrumentos modifican su comportamiento a lo largo de su vida y es común calibrarlos de cuando en cuando. Un instrumento tan sencillo como un termómetro de mercurio se debe calibrar para corregir el error. Por ejemplo, si un reactor está a 70ºC y el instrumento lee 69ºC, el error será de –1ºC.

 El error se define, habitualmente, como Valor de Lectura-Valor Real; si bien podría usarse a la inversa sin mayores confusiones, con tan sólo especificar que opción se usa.
ERROR de NO LINEALIDAD.

Los instrumentos ideales son lineales. De hecho, la mayoría de los sistemas instrumentales comerciales tienen respuesta lineal. Puede ocurrir, sin embargo, que la respuesta no sea estrictamente lineal y aparezca  un error por la no linealidad de la respuesta del instrumento.

Un caso típico que conviene tener en cuenta es el de los electrodos y medidores de pH. La escala de pH resulta lineal pues el potencial de Nernst generado corresponde al logaritmo negativo de la concentración molar de hidrógeno ionizado (H+). A pesar de la sólida definición que sustenta la linealidad del medidor y de la electrónica utilizada para la amplificación, los sistemas (electrodo más medidor) de medición de pH sufren de no linealidades y, en realidad, la relación entre el pH de la solución y el pH medido es más bien como indican los puntos (circulitos) que no como la línea sólida (hipotética respuesta lineal) de la figura a continuación.

 REPETITIBILIDAD.

Especifica la habilidad del instrumento para entregar la misma lectura en aplicaciones repetidas del mismo valor de la variable medida. Así, por ejemplo, si a una misma presión de 25 p.s.i.g., un manómetro de precisión de 1 p.s.i., entrega las lecturas de 25,5; 26; 24,3; y 24 p.s.i.g. su operación es repetible; una lectura de 27 p.s.i.g. indicaría un problema de repetibilidad del instrumento (a menos que conste que fuese un problema de [histéresis](http://mimosa.pntic.mec.es/~pferna37/web/32.htm#_HIST%C3%89RESIS.)).

  
REPRODUCIBILIDAD.

Se refiere a la capacidad del instrumento de mantener una misma lectura cuando el valor de la especie medida está a valor constante. También se utiliza este término para describir la capacidad de entregar el mismo valor medio y desviación estándar al medir repetidamente un mismo valor.

 RESOLUCIÓN.

 Expresa la posibilidad de discriminar entre valores, debido a las graduaciones del instrumento. Se suele hablar de número de dígitos para indicadores numéricos digitales y de porcentaje de escala para instrumentos de aguja.  Por ejemplo los termómetros de baja calidad sólo tienen indicaciones cada 10 ºC, sin subdivisiones, a fin de enfatizar al usuario que el instrumento sólo da una noción y no se debe usar como instrumento de alta [resolución](http://mimosa.pntic.mec.es/~pferna37/web/32.htm#_RESOLUCI%C3%93N.). La resolución está en línea directa relación a la escala del instrumento.

 
RANGO DE MEDIDA.

 Expresa los límites inferior y superior del instrumento. Por ejemplo, los sistemas de medición de pH suelen ser de rango 0 a 14 (aún cuando la "escala" conceptual de pH puede exceder este rango; pero, en soluciones que no llamaríamos "acuosas").

 RANGO de TRABAJO o de OPERACIÓN

 Muchos instrumentos, sobre todo los industriales, permiten definir subrangos de su rango intrínseco, Típico de medidores de pH, subrangos de 0 a 1,4; de 1 a 2,4; de 2 a 3,4; etc. El rango de trabajo mejora la resolución pero no necesariamente la [sensibilidad](http://mimosa.pntic.mec.es/~pferna37/web/32.htm#_Sensibilidad_(sensivility).).
 
BANDA MUERTA.

 Los instrumentos suelen ser insensibles a muy pequeños cambios, porque su sensibilidad así lo impone. Este mismo concepto puede ser visto a la inversa, especificando, en cambio, la banda (en el sentido de espacio) muerta del instrumento, es decir, lo grande que debe ser el cambio de la  medida para que el instrumento reaccione. Este término también se aplica a los rangos de valor de la  medida para los que el instrumento no responde; p.e. temperaturas debajo o sobre el rengo de un termómetro.
 OFFSET O DESPLAZAMIENTO  DEL CERO.

  La lectura en cero suele cambiar por razones asociadas al uso de un instrumento o porque las etapas amplificadoras sufren de deriva en el tiempo (como, por ejemplo, la línea base de un cromatograma). Los instrumentos deben especificar su tolerancia al desplazamiento  del cero y, además, los procedimientos y periodicidad de recalibraciones. Un caso muy típico es el cero de la escala de pH (la concentración molar de H+ es igual a la de OH- a pH 7,00) que se debe recalibrar frecuentemente.
 TIEMPO DE RESPUESTA.

  La medición de cualquier variable de proceso puede implicar una demora, (debida a fenómenos de equilibrio, transporte, etc.) que debe ser definida adecuadamente. Si la medición tiene una cinética más lenta que la de la propia variable, habrá que disponer de sistemas complejos de predicción del valor en lugar de descansar sólo sobre la medición instrumental. Los tiempos de respuesta se definen en base al tiempo necesario para obtener una medida que corresponda al 96% (o cualquier otro porcentaje) del valor final. Los electrodos de pH comunes, por ejemplo, tienen tiempos de respuesta del orden 5 segundos; pero existen electrodos de mejores tiempos de respuesta (electrodos de "Ross"), del orden de un segundo.

 
HISTÉRESIS.

 Algunos instrumentos presentan un fenómeno de "memoria" que impone un histéresis a su respuesta. En particular, un sistema de medición de presión podría indicar los cambios de presión según si la presión anterior era más alta o más baja que la actual, debido a fenómenos de resistencia viscosa al desplazamiento de partes interiores del sensor. Así, una presión de 3 p.s.i.g., por ejemplo, podría leer 3,1 si la presión acaba de bajar, pero 2,9 si esta ha subido. El diagrama tradicional de las respuestas con histéresis consiste de dos curvas, en lugar de la línea recta hipotética.

  
FUNCIÓN DE TRANSFERENCIA.

 Un instrumento se puede caracterizar formalmente mediante su función de transferencia, es decir, por su modelo matemático Entrada/Salida, donde la entrada es el valor real de la propiedad medida y la salida es la lectura en el instrumento. La ganancia deberá ser unitaria; pero tanto la forma dinámica de la respuesta (si oscila, por ejemplo) entre cambios como el tiempo de respuesta pueden ser importantes para la aplicación que se esté diseñando. Las funciones de transferencia de instrumentos de alta calidad suelen estar disponibles desde el fabricante.
