### ISSUE TITLE
 Ejercicio 1 D

### ISSUE THREAD

**Issue by JDGA1997** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-5#6]
#  Ejercicio 1 D

### De ejemplo de las características de 1 sensor real, por ejemplo (temperatura, presión, humedad, aceleración, posición, color, distancia).

**Comment by recursosssbb** [comment]
Ejercicio 1 D
De ejemplo de las características de 1 sensor real, por ejemplo (temperatura, presión, humedad, aceleración, posición, color, distancia).

**Tipos de sensores**  Según el tipo de variable que deban medir o detectar encontramos 12 tipos de sensores que 

**1.** Sensor de temperatura: El sensor de temperatura nos proporciona información de la temperatura del exterior (es decir, del medio), mediante impulsos eléctricos. Estos sensores permiten controlar la temperatura de ambiente.
Los sensores de temperatura son en realidad resistencias, cuyo valor asciende con la temperatura, o disminuye con ella. En el primer caso, lo denominamos termistor PTC, y en el segundo, termistor NTC.  A su vez, los sensores de temperatura pueden ser de diferentes tipos: de contacto, de no-contacto, mecánicos y eléctricos.

- Un ejemplo de sensor de temperatura es un termómetro (el clásico, de mercurio) (en este caso, se trata de un sensor mecánico). Este tipo de sensores son especialmente utilizados en el sector industrial; su objetivo es controlar la temperatura de las diferentes máquinas, entre otros.

**2.** Sensores de luz: Otros tipos de sensores son los de la luz; en este caso, se trata de dispositivos electrónicos que responden al cambio en la intensidad de la luz. Es decir, permiten determinar la presencia de luz. Así, este tipo de sensores detectan la luz visible (es decir, la que percibimos con el ojo), y además, responden en función de su intensidad.

- Un ejemplo de sensor de luz es la célula fotoeléctrica, un dispositivo que transforma la energía lumínica en energía eléctrica, a través de un efecto denominado “efecto fotoeléctrico”. Este dispositivo permite generar energía solar fotovoltaica.

**3.** Sensores de distancia: Los sensores de distancia son dispositivos que permiten medir distancias; además, dependiendo del tipo, también pueden utilizarse como sensores de presencia o movimiento.

- Un ejemplo de sensor de distancia es el infrarrojo, basado en un sistema de emisión y recepción de radiación. También encontramos, como ejemplo de sensor de distancia, el sensor ultrasónico, que envía pulsos haciendo que las ondas reboten en la superficie.

**4.** Sensores de proximidad: Los siguientes tipos de sensores, los de proximidad, consisten en transductores que detectan la presencia de objetos (obstáculos, personas…) sin necesidad de un contacto. En algunos casos también se pueden configurar para que midan la distancia.

**5.** Sensores de posición: Los sensores de posición nos permiten determinar qué ubicación tiene un determinado objeto. Como característica de los mismos, encontramos que generalmente disponen de un sistema electrónico particular, a fin de que puedan determinar la ubicación con la máxima precisión.

**6.** Sensores de color: Los sensores de color convierten la luz en frecuencia, a fin de poder detectar los colores de determinados objetos a partir de su radiación reflejada; lo que hacen es comparar estas radiaciones con los valores de referencia guardados.
Estos tipos de sensores emiten tres tipos de luz: roja, verde y azul, y lo hacen sobre los objetos que pretenden analizar. Finalmente, estos dispositivos generan una señal de salida (una respuesta).

**7.** Sensores de la humedad: Estos tipos de sensores lo que hacen es medir la humedad relativa, así como la temperatura del ambiente. Concretamente, actúan emitiendo una señal acondicionada, gracias a una serie de circuitos integrados de que disponen. Los sensores de humedad captan las señales del ambiente para detectar estos parámetros (humedad y temperatura). Además, el margen de error que tienen suele ser muy pequeño.

- Por otro lado, a modo de ejemplo, este tipo de sensores se pueden aplicar para detectar el nivel de líquido en un depósito; también se utilizan en sistemas de riego de jardines, con el objetivo de determinar cuándo las plantas necesitan riego y cuándo no.

**8.** Sensores de velocidad: También conocidos como “velocímetros”, los sensores de velocidad permiten detectar la velocidad de un objeto (generalmente un vehículo).

- Un ejemplo de ellos son los radares, que detectan si un vehículo iba a una velocidad superior a la permitida.

**9.** Sensores de sonido:  Los siguientes tipos de sensores son los de sonido; se encargan de captar los sonidos del exterior (ambiente), a través de un micrófono o de un sistema de sonar. Las ondas de sonido que reciben estos sensores se propagan por el aire del medio y después son detectadas por los sensores. Se utilizan normalmente para recibir estímulos del exterior en forma de órdenes (provenientes de personas), de forma remota.

**10.** Sensores de contacto: Los sensores de contacto tienen la finalidad de detectar el final del recorrido de componentes mecánicos (o en otras palabras, su posición límite). Un ejemplo de ellos son: puertas que se abren de forma automática, que cuando ya están completamente abiertas, el motor que las acciona “sabe” que debe detenerse.

**11.** Sensores ópticos: En este caso, estos tipos de sensores permiten detectar la presencia de un objeto (o de una persona) que interrumpe un haz de luz que llega hasta el sensor.

- Un ejemplo de ellos (y los principales) son las llamadas “fotorresistencias” (también denominadas LDR). Las LDR se utilizan especialmente en robótica, con el objetivo de regular el movimiento de los robots y de detener su movimiento en el momento en el que estén a punto de tropezar con algún otro objeto.

**12.** Sensores magnéticos: Los sensores magnéticos actúan detectando los campos magnéticos que provocan las corrientes eléctricas o los imanes.

- Un ejemplo de estos tipos de sensores es el interruptor Reed, que consiste en dos láminas metálicas introducidas en el interior de una cápsula; dichas láminas están en presencia de un campo magnético, y se atraen entre ellas (es decir, cierran el circuito).
